### PR TITLE
change ASP tags into PHP

### PR DESCRIPTION
**Pull request by joereynolds**
I'm not sure why we have ASP includes, why not just use PHP?
I've only changed a few just in case there's a legitimate reason to keep the ASP. If not, I'll go through the rest of the files

### CODE REVIEW

**Comment by metulburr** [comment]
is there a legitimate reason to prefer PHP over ASP?

**Comment by joereynolds** [comment]
Well everything else is already in php isn't it? Seems odd to factor in another language for no reason?

**Comment by metulburr** [comment]
I am not fond of web design and was trying to just get the site up and running. So i used what i knew. And i dont know php. So that is why. I dont really care which it uses as long as it works. The whole website is pieced together as i am quite the novice with web design.

**Comment by joereynolds** [comment]
That's not a problem, my only suggestion is maybe using one technology over several? It makes it easier for people wanting to contribute to the codebase too.

**Comment by metulburr** [comment]
Have at it. I'll pull it as long as it works. If it bombs i can always revert

**Pull request closed without merging**
